# Generated by Django 3.2.16 on 2022-11-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('unit_price', models.CharField(max_length=255)),
                ('order_date', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
